using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace part3.classes
{
    internal class Class2
    {
    }
}

namespace CybersecurityAwarenessBot.Models
{
    /// <summary>
    /// Represents a single entry in the activity log
    /// </summary>
    public class ActivityLogEntry
    {
        /// <summary>
        /// Unique identifier for the log entry (auto-generated by database)
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Type of action performed (e.g., "Task Added", "Quiz Started")
        /// </summary>
        public string Action { get; set; }

        /// <summary>
        /// Detailed description of what happened
        /// </summary>
        public string Details { get; set; }

        /// <summary>
        /// When the action occurred
        /// </summary>
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// Default constructor
        /// </summary>
        public ActivityLogEntry()
        {
            Action = string.Empty;
            Details = string.Empty;
            Timestamp = DateTime.Now;
        }

        /// <summary>
        /// Constructor to create a log entry
        /// </summary>
        /// <param name="action">Type of action</param>
        /// <param name="details">Detailed description</param>
        public ActivityLogEntry(string action, string details)
        {
            Action = action;
            Details = details;
            Timestamp = DateTime.Now;
        }

        /// <summary>
        /// Returns a formatted string representation of the log entry
        /// </summary>
        public override string ToString()
        {
            return $"[{Timestamp:yyyy-MM-dd HH:mm}] {Action}: {Details}";
        }
    }
}