using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace part3.classes { }


namespace CybersecurityAwarenessBot.Models
{
    /// <summary>
    /// Represents a cybersecurity task that the user needs to complete
    /// </summary>
    public class TaskItem
    {
        /// <summary>
        /// Unique identifier for the task (auto-generated by database)
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Short title/name of the task (e.g., "Update passwords")
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Detailed description of what the task involves
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Optional date when the user wants to be reminded
        /// </summary>
        public DateTime? ReminderDate { get; set; }

        /// <summary>
        /// Whether the task has been completed by the user
        /// </summary>
        public bool IsCompleted { get; set; }

        /// <summary>
        /// When the task was created
        /// </summary>
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Default constructor initializes empty task
        /// </summary>
        public TaskItem()
        {
            Title = string.Empty;
            Description = string.Empty;
            CreatedAt = DateTime.Now;
        }

        /// <summary>
        /// Constructor to create a new task with required details
        /// </summary>
        /// <param name="title">Task title</param>
        /// <param name="description">Task description</param>
        /// <param name="reminderDate">Optional reminder date</param>
        public TaskItem(string title, string description, DateTime? reminderDate = null)
        {
            Title = title;
            Description = description;
            ReminderDate = reminderDate;
            IsCompleted = false;
            CreatedAt = DateTime.Now;
        }
    }
}